### PR TITLE
realted-item

### PR DESCRIPTION
**Pull request by yuxinlu1**
add related-item

### CODE REVIEW

**Review by squeakypickles33 — COMMENTED** [review]
Folder name should be RelatedItems (no spaces and plural with s at the end) along with the module names as well. File should be named index.jsx to be standard with the other widgets.

**Comment by squeakypickles33** [comment]
Also remember that your branch names should prefix as ri-whateverfeatureyouredoinghere

**Review by justcord10 — CHANGES_REQUESTED** [review]
The folder name should not have spaces in it, it should be RelatedItem to match the naming conventions. 
Also make sure the title of your pull request matches the ticket exactly, it should be "[M] Create branch with agreed upon folder structure, then PR #21"
Another thing to be aware of is that when naming branches related to your component they should be of the form ri-folder-structure-setup ('ri-' followed by the feature name that you are adding)

**Comment by squeakypickles33** [comment]
Lastly change RelatedItem to RelatedItems. Otherwise looks good

**Pull request closed without merging**
