### PR TITLE
Ri folder structure

### PR DESCRIPTION
**Pull request by yuxinlu1**

### CODE REVIEW

**Review by squeakypickles33 — CHANGES_REQUESTED** [review]
Looks better, branch naming convention good. Next time you do not need to close the PR, just know to keep naming convention the same for future branches. 
Just change RelatedItem to RelatedItems (with an s at the end) of the folder and module names in your code

**Comment by justcord10** [comment]
After this ticket just make sure to match the name of the pull request with the name of the ticket on trello.

**Comment by yuxinlu1** [comment]
>changed

**Review by squeakypickles33 — CHANGES_REQUESTED** [review]
Last thing is the folder name should also be RelatedItems with the s

**Review by squeakypickles33 — APPROVED** [review]
Approved thanks

**Pull request merged**
